# Generated by Django 4.2.5 on 2024-08-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festivalname', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='festival/images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
