# Generated by Django 5.2.1 on 2025-05-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khschool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='carousel/images/')),
                ('button_text', models.CharField(default='Learn More', max_length=50)),
                ('button_link', models.CharField(default='/about', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Order in which to display the carousel image')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carousel Image',
                'verbose_name_plural': 'Carousel Images',
                'ordering': ['order'],
            },
        ),
    ]
