# Generated by Django 5.2.1 on 2025-05-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khschool', '0002_carouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='button_link',
            field=models.CharField(choices=[('/', 'Home'), ('/aboutSchool/', 'About School'), ('/brief/', 'Executive Brief'), ('/gallery/', 'Gallery'), ('/contact/', 'Contact Us'), ('/chandkheda/', 'Chandkheda Campus'), ('/chattral/', 'Chattral Campus'), ('/iffco/', 'IFFCO Campus'), ('/kadi/', 'Kadi Campus'), ('#', 'No Link (Stay on Page)')], default='/', max_length=100),
        ),
    ]
