# Generated by Django 5.2.1 on 2025-05-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khschool', '0003_alter_carouselimage_button_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celebration',
            options={'ordering': ['-date'], 'verbose_name': 'Celebration', 'verbose_name_plural': 'Celebrations'},
        ),
        migrations.AddField(
            model_name='celebration',
            name='celebration_type',
            field=models.CharField(choices=[('festival', 'Festival'), ('event', 'School Event'), ('sports', 'Sports Event'), ('cultural', 'Cultural Event'), ('academic', 'Academic Event'), ('other', 'Other')], default='festival', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='celebration',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='celebration',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Feature on Homepage'),
        ),
        migrations.AlterField(
            model_name='celebration',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='celebration',
            name='festivalname',
            field=models.CharField(max_length=255, verbose_name='Celebration Name'),
        ),
        migrations.AlterField(
            model_name='celebration',
            name='image',
            field=models.ImageField(upload_to='festival/images/', verbose_name='Image'),
        ),
    ]
