# Generated by Django 5.2.1 on 2025-05-30 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khschool', '0004_alter_celebration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebration',
            name='image',
            field=models.ImageField(upload_to='festival/images/', verbose_name='Main Image'),
        ),
        migrations.CreateModel(
            name='CelebrationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='festival/gallery/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('celebration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khschool.celebration')),
            ],
            options={
                'verbose_name': 'Celebration Photo',
                'verbose_name_plural': 'Celebration Photos',
                'ordering': ['celebration', 'order'],
            },
        ),
    ]
