# Generated by Django 5.2.1 on 2025-06-01 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khschool', '0006_add_supabase_image_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Gallery Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('festival', 'Festival'), ('event', 'School Event'), ('sports', 'Sports Event'), ('cultural', 'Cultural Event'), ('academic', 'Academic Event'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/', verbose_name='Thumbnail')),
                ('thumbnail_url', models.CharField(blank=True, max_length=500, verbose_name='Thumbnail (Supabase)')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Feature on Homepage')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/images/', verbose_name='Image')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='Image (Supabase)')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khschool.gallery')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['gallery', 'order', '-date_added'],
            },
        ),
    ]
