# Generated by Django 5.2.1 on 2025-07-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khschool', '0007_gallery_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='campus_branch',
            field=models.CharField(choices=[('chattral', 'Chattral Campus'), ('kadi', 'Kadi Campus'), ('iffco', 'IFFCO Campus'), ('chandkheda', 'Chandkheda Campus'), ('general', 'General/Other')], default='general', max_length=20, verbose_name='Campus Branch'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='show_on_campus_page',
            field=models.BooleanField(default=False, verbose_name='Show on Campus Page (4-5 Featured Photos)'),
        ),
    ]
