# Generated by Django 5.2.1 on 2025-07-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khschool', '0008_gallery_campus_branch_gallery_show_on_campus_page'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['campus_branch', 'show_on_campus_page'], name='khschool_ga_campus__0f52d1_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['is_featured', '-date_created'], name='khschool_ga_is_feat_23b767_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['category', '-date_created'], name='khschool_ga_categor_7ebf33_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['campus_branch', 'category'], name='khschool_ga_campus__9bb611_idx'),
        ),
    ]
