# Generated by Django 5.2.1 on 2025-07-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khschool', '0009_gallery_khschool_ga_campus__0f52d1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_branch', models.CharField(choices=[('chattral', 'Chattral Campus'), ('kadi', 'Kadi Campus'), ('iffco', 'IFFCO Campus'), ('chandkheda', 'Chandkheda Campus')], max_length=20, verbose_name='Campus Branch')),
                ('title', models.CharField(max_length=200, verbose_name='Photo Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('classrooms', 'Classrooms'), ('playground', 'Playground'), ('library', 'Library'), ('labs', 'Laboratories'), ('events', 'Events & Activities'), ('sports', 'Sports'), ('cultural', 'Cultural Activities'), ('facilities', 'Facilities'), ('campus_life', 'Campus Life'), ('other', 'Other')], default='other', max_length=20, verbose_name='Photo Category')),
                ('image', models.ImageField(blank=True, null=True, upload_to='branch_photos/', verbose_name='Photo')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='Photo (Supabase)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Show on Campus Page')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
            ],
            options={
                'verbose_name': 'Branch Photo',
                'verbose_name_plural': 'Branch Photos',
                'ordering': ['campus_branch', 'order', '-date_uploaded'],
                'indexes': [models.Index(fields=['campus_branch', 'is_featured'], name='khschool_br_campus__bd01df_idx'), models.Index(fields=['campus_branch', 'category'], name='khschool_br_campus__6b936e_idx')],
            },
        ),
    ]
